#!/bin/bash
#
# Script chargé de :
# - retourner horizontallement ou verticalement les photos
# - renommer photos & videos par date heure et minute de prise de vue
# - classer photos & videos dans une structure de répertoires datés
# - transférer photos & videos sur zekra au bon endroit
# - effacer photos & videos un par un une fois transférées sur zekra
#

sudo apt-get install -y jhead libimage-exiftool-perl rsync

set -e

ORIG=/home/kerphi/freebox/Photos/GT-I9100/Camera
ORIG=/home/kerphi/freebox/Photos/Nexus\ 5/Camera
ORIG=/media/kerphi/9016-4EF8/DCIM/101CANON

# nettoyage des fichiers appercus des vidéos
rm -f *.THM
# retourne la photo dans le bon sens (vertical ou horizontal) 
# en fonction de la métadonnées exif renseignée par l'appareil photo
jhead -autorot -c *.JPG
# range les photos par répertoires datés
exiftool '-FileName<DateTimeOriginal' -d %Y-%m_Famille/%Y%m%d-%Hh%M_%%f.%%e ./*.JPG
#exiftool '-FileName<GPSDateTime' -d %Y-%m_Famille/%Y%m%d-%Hh%M_%%f.%%e ./*.jpg
# range les videos par répertoires datés
exiftool '-FileName<MediaCreateDate'  -d %Y-%m_Famille/%Y%m%d-%Hh%M_%%f.%%e ./*.MOV

# transfert optimisé des répertoires datés sur zekra
for PHOTODIR in $(find . -maxdepth 1 -type d -path "./20*_*")
do
  ANNEE=$(echo $PHOTODIR | sed 's#.*\(20[0-9]\{2\}\).*#\1#g')
  rsync -ravhp --chmod=777 --remove-source-files "$PHOTODIR" zekra:/mnt/zekra/photos/$ANNEE/
done
