#!/bin/bash
#
# Script chargé de :
# - retourner horizontallement ou verticalement les photos
# - renommer photos & videos par date heure et minute de prise de vue
# - classer photos & videos dans une structure de répertoires datés
# - transférer photos & videos sur zekra au bon endroit
# - effacer photos & videos un par un une fois transférées sur zekra
#

sudo apt-get install -y jhead libimage-exiftool-perl rsync

set -e

# transfert optimisé des répertoires datés sur zekra
for PHOTODIR in $(find . -maxdepth 1 -type d -path "./20*_*")
do
  ANNEE=$(echo $PHOTODIR | sed 's#.*\(20[0-9]\{2\}\).*#\1#g')
  rsync -ravhp --chmod=777 --remove-source-files "$PHOTODIR" zekra:/mnt/zekra/photos/$ANNEE/
done
